### ISSUE TITLE
File Does Not Launch on Manjaro KDE

### ISSUE THREAD

**Issue by sh9r** [lucasscvvieira/spotify-appimage#1]
After integrating with appimage launcher, the appimage does not launch. Running Manjaro with KDE Plasma as the DE. If you need more info just tell me

**Comment by lukerops** [comment]
I had the same problem with Fedora 34. After debugging, I realized that some dependencies were missing.

Try again with the latest build.

**Comment by sh9r** [comment]
It works now!
